# Generated by Django 6.1.1 on 2026-09-06 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the director's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Enter the director's last name", max_length=100)),
                ('year_of_birth', models.PositiveIntegerField(blank=True, help_text="Enter the director's year of birth", null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the movie title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the movie')),
                ('release_date', models.DateField(help_text='Enter the release date of the movie')),
                ('director', models.ForeignKey(help_text='Select the director for this movie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this movie', to='catalog.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False, help_text='Has the user watched this movie?')),
                ('movie', models.ForeignKey(help_text='Select the movie', on_delete=django.db.models.deletion.CASCADE, to='catalog.movie')),
                ('user', models.ForeignKey(help_text='Select the user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'movie'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie')],
            },
        ),
    ]
