# Generated by Django 6.1.1 on 2026-09-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_director_movie_usermovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=2000, help_text='Enter the release year of the movie'),
            preserve_default=False,
        ),
    ]
